### ISSUE TITLE
Error: panicked at 'assertion failed: _was_removed', src/transactions/light_pool.rs:857:21

### ISSUE THREAD

**Issue by librelois** [paritytech/smoldot#1966]
I test smoldot light wasm client with a local blockchain of the [Duniter-v2S](https://git.duniter.org/nodes/rust/duniter-v2s) project.

It seems that smoldot is able to load my runtime and connect to my substrate node in p2p.

Then I submit a transaction via polkadotjs, it is well received by smoldot and well transmitted to my full node substrate, but once the transaction is written in a block, it crashes: 

```
[01:26:17.443] [smoldot] Chain initialization complete for gdev. Name: "?dev". Genesis hash: 0x80e2?3d9c. State root hash: 0x637e89970651051a9e1c15bfcb9adf4ef3864e870e1196d08219752f84b2bbba. Network identity: 12D3KooWEzhJ9xUop72hXPNemCqYERUhY5Je7VmfYXg5Mi8Ct8if. Starting at block #0 (0x80e2?3d9c)
[01:26:17.547] [sync-service-gdev] GrandPa warp sync finished to #34 (0xa083?d12d)
[01:26:17.548] [runtime-gdev] Finalized block runtime ready. Spec version: 100. Size of `:code`: 380 kiB.
[01:26:17.932] [sync-service-gdev] Block announce header height (#34) from 12D3KooWRQBZgbJD6xyPMKXDdbWoxRBULWHCEmXP1yVMuHv92P9q is below finalized block
New JSON-RPC client connected: ::ffff:127.0.0.1.
[01:27:17.442] [smoldot] Current memory usage: 35.9 MiB. Average download: 7.3 kiB/s. Average upload: 244 B/s.
[01:27:47.443] [connections] Problem during discovery on gdev: NotConnected
[01:28:17.442] [smoldot] Current memory usage: 36.0 MiB. Average download: 3.1 kiB/s. Average upload: 825 B/s.
[01:28:25.244] [tx-service-gdev] Successfully validated transaction 0x5a9f?7508
[01:28:27.443] [connections] Problem during discovery on gdev: NotConnected
Smoldot has panicked. This is a bug in smoldot. Please open an issue at https://github.com/paritytech/smoldot/issues with the following message:
Error: panicked at 'assertion failed: _was_removed', /home/elois/dev/paritytech/smoldot/src/transactions/light_pool.rs:857:21
    at panic (file:///home/elois/dev/paritytech/smoldot/bin/wasm-node/javascript/dist/worker/bindings-smoldot-light.js:33:19)
    at _ZN18smoldot_light_wasm4init5panic17heae09a5ed13456cbE (<anonymous>:wasm-function[1540]:0x17a198)
    at _ZN18smoldot_light_wasm4init4init28_$u7b$$u7b$closure$u7d$$u7d$17h0885dfa9e5ef55ebE (<anonymous>:wasm-function[1451]:0x1677c0)
    at _ZN3std9panicking20rust_panic_with_hook17heefe90fce7240a03E (<anonymous>:wasm-function[5199]:0x3eb693)
    at _ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17h4f5bcef500c8e46dE (<anonymous>:wasm-function[5188]:0x3eae83)
    at _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17h53dbd65c57a9d0e6E (<anonymous>:wasm-function[5187]:0x3eadfa)
    at rust_begin_unwind (<anonymous>:wasm-function[5198]:0x3eb585)
    at _ZN4core9panicking9panic_fmt17h92e73467e6a2c091E (<anonymous>:wasm-function[5314]:0x3f7431)
    at _ZN4core9panicking5panic17h1861d03b28464ac7E (<anonymous>:wasm-function[5302]:0x3f2609)
    at _ZN7smoldot12transactions10light_pool26LightPool$LT$TTx$C$TBl$GT$25prune_finalized_with_body17h9d73e0ea97839e1aE (<anonymous>:wasm-function[1893]:0x1aeeb5)
Error during JSON-RPC request: Error: Error: panicked at 'assertion failed: _was_removed', /home/elois/dev/paritytech/smoldot/src/transactions/light_pool.rs:857:21
```

**Comment by tomaka** [comment]
Thanks for the report!

This is a duplicate of https://github.com/paritytech/smoldot/issues/1433, but we can leave it open.

**Comment by tomaka** [comment]
See comment: https://github.com/paritytech/smoldot/pull/1972#issuecomment-1026216539

**Comment by librelois** [comment]
More logs with one transaction (a simple balances.transfer) that never inserted:

[smoldot1.log](https://github.com/paritytech/smoldot/files/7990397/smoldot1.log)
 
Also note that now I can't run smoldot during the 1st epoch (index 0), I get the error `UnexpectedBabeSlotStartNumber`.

tested on v0.5.17

**Comment by librelois** [comment]
Also I have a regression, now in all cases the transactions are never registered in block, whether I run smoldot during the 1st epoch or after the 1st epoch.

**Comment by tomaka** [comment]
The `UnexpectedBabeSlotStartNumber` error should be fixed by https://github.com/paritytech/smoldot/pull/1990.
The `UnexpectedBabeFinalizedEpoch` error requires some refactoring, which I'm not going to do now as the error is IMO not problematic in practice.

> Also I have a regression, now in all cases the transactions are never registered in block, whether I run smoldot during the 1st epoch or after the 1st epoch.

My bet would be that the transaction announcement somehow doesn't work, but I haven't investigated.

**Comment by librelois** [comment]
I continued the investigation by first repeating the test several times in different conditions and on different commits to determine in which case the problem occurs or not, and I had too many inconsistencies, so it seems that the problem occurs randomly.

So I added myself some logs to the source code to identify the cause, and indeed it's the transaction announcement that fails, because the substream dedicated to the transactions has been reset at this line: 

https://github.com/paritytech/smoldot/blob/main/src/libp2p/connection/established/substream.rs#L1136

Adding more logs, I noticed that the `process_substream` function is called very often at very short intervals. And that in some cases, it resets the transaction substream via this line: 

https://github.com/paritytech/smoldot/blob/main/src/libp2p/connection/established.rs#L463

I've started working on integrating smoldot in duniter-v2s end2end tests, as we'd like to make sure our blockchain will be compatible with smoldot, it's not merged yet (work in progress) but it's on that branch: https://git.duniter.org/nodes/rust/duniter-v2s/-/tree/elois-smoldot

I deploy a local network with 1 full node (duniter) and 1 light node (smoldot) with this script : ./scripts/run_smoldot_tests.sh

Then, the logs are in files in the `end2end-tests/` folder. The RPC port is in the file name.

I think that the smoldot light node project is very important, I would like to help but unfortunately I lack time and knowledge.

**Comment by librelois** [comment]
Thank @tomaka for #1993, unfortunately this does not solve the problem.

I added a log line in service where you command to reopen the substream, and it is never printed:

```rust
// The state of notification substreams other than block announces must
                    // always match the state of the block announces.
                    // Therefore, if the peer is considered open, try to reopen the substream that
                    // has just been closed.
                    // TODO: cloning of peer_id :-/
                    if guarded
                        .open_chains
                        .contains(&(peer_id.clone(), chain_index))
                    {
                         // TEMPORARY LOG HERE --v
                        log::info!("set_peer_notifications_out_desired({}, {}, DesiredReset)", &peer_id, notifications_protocol_index);
                        self.inner
                            .set_peer_notifications_out_desired(
                                peer_id,
                                *notifications_protocol_index,
                                peers::DesiredState::DesiredReset,
                            )
                            .await;
                    }
```

I have added other logs elsewhere that are well printed, including this one:

```rust
pub async fn announce_transaction(
        self: Arc<Self>,
        chain_index: usize,
        transaction: &[u8],
    ) -> Vec<PeerId> {
        let mut sent_peers = Vec::with_capacity(16); // TODO: capacity?

        // TODO: keep track of which peer knows about which transaction, and don't send it again

        for target in self.peers_list().await {
            log::info!("Announce transaction to peer {}", target);
            if let Err(e) = self
                .inner
                .network
                .announce_transaction(&target, chain_index, &transaction)
                .await
            {
                log::info!("Fail to annonce transaction to peer {}: {}", target, e); // <-- TEMPORARY LOG HERE
            } else {
                sent_peers.push(target);
            }
        }

        sent_peers
    }
```

My log: 

```log
[19:13:21.092] [sync-service-gdev_local_testnet] GrandPa warp sync finished to #1 (0x5efe?975d)
[19:13:21.092] [runtime-gdev_local_testnet] Finalized block runtime ready. Spec version: 100. Size of `:code`: 380 kiB.
New JSON-RPC client connected: ::ffff:127.0.0.1.
New JSON-RPC client connected: ::ffff:127.0.0.1.
[19:13:43.795] [tx-service-gdev_local_testnet] Successfully validated transaction 0x116b?3b2a
[19:13:43.795] [smoldot_light_base::network_service] Fail to annonce transaction to peer 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp: queue_notification:open_state: Some(Closed)
JSON-RPC client ::ffff:127.0.0.1 disconnected.
[19:14:00.191] [tx-service-gdev_local_testnet] Successfully validated transaction 0x116b?3b2a
[19:14:00.191] [smoldot_light_base::network_service] Fail to annonce transaction to peer 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp: queue_notification:open_state: Some(Closed)
[19:14:04.142] [smoldot] Smoldot v0.5.18. Current memory usage: 36.2 MiB. Average download: 103 kiB/s. Average upload: 2.4 kiB/s.
```

So it seems that the substream is closed but never reopened.
Also, I think that the substream is closed by smoldot itself because of an aggressive reset strategy, and that it has nothing to do with my full node which always accepts the connection.

But it's too long to try to debug by adding logs by hand in the code, we would really need a native version to be able to use a debugger :)

**Comment by tomaka** [comment]
> But it's too long to try to debug by adding logs by hand in the code, we would really need a native version to be able to use a debugger :)

I'm preferably going the route of more and better logging instead.
If an end user encounters a bug, we can ask them to open an issue with their logs, but we can't ask them to use a debugger.

**Comment by tomaka** [comment]
I'm only testing with Westend, but I can't reproduce any problem with transactions anymore.

**Comment by librelois** [comment]
I just retested on commit cffed04bc36a91ee1699d9f1b33b21aa2968dfbf and I still have the same issue. 
I see that the logs start with `[smoldot] Smoldot v0.6.1`, so I think I'm based on the right commit now :) 

Here the logs at debug level: [debug.log](https://github.com/paritytech/smoldot/files/8068946/debug.log)
